# Generated by Django 4.2.7 on 2025-08-25 03:30

import django.core.validators
from django.db import migrations, models
import pims.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_prp_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customuser',
            new_name='users_custo_is_prp__36d2f6_idx',
            old_name='users_customuser_is_prp_managed_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='users_custo_is_prp__31c875_idx',
            old_name='users_customuser_prp_sync_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, help_text='Job designation/position in the Parliament Secretariat. For PRP users: maps to PRP designationEng', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(help_text='Unique employee identification number (numbers only). For PRP users: maps to PRP userId', max_length=20, unique=True, validators=[pims.utils.validators.validate_employee_id]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active_employee',
            field=models.BooleanField(default=True, help_text='Designates whether this user is an active employee. For PRP users: maps to PRP status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='office',
            field=models.CharField(blank=True, help_text='Office within Bangladesh Parliament Secretariat. For PRP users: maps to PRP department nameEng', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number. For PRP users: maps to PRP mobile', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile picture for identification. For PRP users: converted from PRP photo', null=True, upload_to='user_images/', validators=[pims.utils.validators.validate_user_image]),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users_customuser',
        ),
    ]
