# Generated by Django 4.2.7 on 2025-08-17 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='provider',
            field=models.ForeignKey(help_text='Warranty provider', on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='device',
            field=models.ForeignKey(help_text='Device this QR code represents', on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='devices.device'),
        ),
        migrations.AddField(
            model_name='devicesubcategory',
            name='category',
            field=models.ForeignKey(help_text='Parent category', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='devices.devicecategory'),
        ),
        migrations.AddField(
            model_name='device',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this device record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='current_location',
            field=models.ForeignKey(blank=True, help_text='Current physical location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='locations.location'),
        ),
        migrations.AddField(
            model_name='device',
            name='parent_device',
            field=models.ForeignKey(blank=True, help_text='Parent device if this is a component (e.g., RAM belongs to Desktop)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='devices.device'),
        ),
        migrations.AddField(
            model_name='device',
            name='subcategory',
            field=models.ForeignKey(help_text='Device subcategory', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.devicesubcategory'),
        ),
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.ForeignKey(help_text='Vendor who supplied this device', on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='vendors.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='warranty',
            unique_together={('device', 'warranty_type', 'provider', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='devicesubcategory',
            unique_together={('category', 'code')},
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_id'], name='devices_dev_device__e2c19e_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='devices_dev_serial__4a3e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='devices_dev_status_bbf58f_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type'], name='devices_dev_device__0d8d82_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['subcategory', 'status'], name='devices_dev_subcate_aa7dfa_idx'),
        ),
    ]
