# Generated by Django 4.2.7 on 2025-08-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='depreciation_rate',
        ),
    ]
