# Generated by Django 4.2.7 on 2025-08-17 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who made the assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_location',
            field=models.ForeignKey(blank=True, help_text='Location where device will be used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_assignments', to='locations.location'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_to',
            field=models.ForeignKey(help_text='User receiving the device assignment', on_delete=django.db.models.deletion.CASCADE, related_name='device_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='device',
            field=models.ForeignKey(help_text='Device being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='devices.device'),
        ),
        migrations.AddIndex(
            model_name='assignmentqrcode',
            index=models.Index(fields=['assignment', 'is_active'], name='assignments_assignm_27582b_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentqrcode',
            index=models.Index(fields=['qr_code_id'], name='assignments_qr_code_b0980c_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assignment_id'], name='assignments_assignm_cf6c53_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['device', 'status'], name='assignments_device__735190_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assigned_to', 'status'], name='assignments_assigne_8bc493_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assigned_date', 'status'], name='assignments_assigne_14b7ac_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['expected_return_date', 'status'], name='assignments_expecte_815a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['is_active', 'status'], name='assignments_is_acti_5a5465_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('status', 'ASSIGNED')), fields=('device',), name='unique_active_device_assignment'),
        ),
    ]
