# Generated by Django 4.2.7 on 2025-08-17 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this maintenance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this maintenance record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='device',
            field=models.ForeignKey(help_text='Device being maintained', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='devices.device'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='External vendor providing service (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_services', to='vendors.vendor'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['device', 'status'], name='pims_mainte_device__c46693_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['start_date', 'expected_end_date'], name='pims_mainte_start_d_f005f2_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['vendor', 'status'], name='pims_mainte_vendor__b037b8_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['maintenance_type', 'priority'], name='pims_mainte_mainten_48976d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['created_at'], name='pims_mainte_created_97d814_idx'),
        ),
    ]
